steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t us-west1-docker.pkg.dev/tienda-ms-452101/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DB_URL_NEON=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-west1-docker.pkg.dev/tienda-ms-452101/image-registry/orders-ms',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/416054606859/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'